/**
 * src/lib/data.ts — the ONE place /data enters the application.
 *
 * Components never import from `@data/...` and never read a JSON file. They call a
 * hook from `src/store/selectors.ts`, which reads from here. That single seam is
 * what makes a schema change a one-file edit, and it is why `check:literals` can
 * be confident that a number appearing in a component came from the physics model.
 *
 * The JSON is imported at BUILD time, not fetched. There is no loading state
 * anywhere in this app because nothing loads — see plan/04 §4. If you ever find
 * yourself wanting a spinner, you have accidentally introduced a runtime fetch.
 *
 * On the casts below: `npm run validate:data` already parses every one of these
 * files against the same Zod schemas and asserts I1–I16, and it runs in `prebuild`.
 * Re-parsing at runtime would cost startup time to re-prove something the build
 * already refused to ship without. The cast is safe precisely because the gate exists.
 */

import farmJson from '@data/farm.json';
import telemetryClientJson from '@data/telemetry_client.json';
import eventsJson from '@data/events.json';
import forecastJson from '@data/forecast.json';
import queueJson from '@data/repair_queue.json';
import cellgridJson from '@data/evidence/b17_cellgrid.json';
import artefactsJson from '@data/artefacts.json';
import panelTexturesJson from '@data/panel_textures.json';

import { unpackTelemetry, type PackedTelemetry } from './telemetryPack';
import type {
  AgentCache, CellGrid, DemoEvent, Detection, Farm, Forecast, PanelArray,
  RepairTask, TelemetryFrame,
} from './types';

export const farm = farmJson as unknown as Farm;
export const events = eventsJson as unknown as DemoEvent[];

/**
 * The demo's 91 frames, rebuilt from the packed form.
 *
 * `telemetry.json` is still the source of truth and `validate:data` still asserts
 * every invariant against it — but it is 1.6 MB, and importing it here put all of
 * it in the CLIENT bundle, where the dev server truncated it on about half of all
 * loads. The page then rendered perfectly and ignored every click, which is the
 * worst way for a demo to fail. See src/lib/telemetryPack.ts.
 *
 * The packed file is generated by `npm run pack:telemetry`, which refuses to write
 * unless unpacking reproduces telemetry.json byte for byte. So this is the same
 * data, not a summary of it.
 */
export const telemetry: TelemetryFrame[] =
  unpackTelemetry(telemetryClientJson as unknown as PackedTelemetry);
export const forecast = forecastJson as unknown as Forecast;
export const repairQueue = queueJson as unknown as RepairTask[];
export const cellGrid = cellgridJson as unknown as CellGrid;

/** Every array, flattened, in map order. */
export const panels: PanelArray[] = farm.zones.flatMap((z) => z.panels);

const panelById = new Map(panels.map((p) => [p.id, p]));
export const getPanel = (id: string): PanelArray | undefined => panelById.get(id);

/**
 * Artefacts that arrive in later phases, written by `scripts/sync_artefacts.mjs`
 * on every `predev` / `prebuild`.
 *
 * A manifest rather than optional imports, because a bundler cannot import a file
 * that does not exist yet and these land across three different phases. One import
 * that is always present, with nulls inside it.
 *
 * plan/04 §4: an absent slot renders as ABSENT — never a placeholder box, never a
 * stub file. Until Colab lands, the RGB thumbnail simply does not appear, which is
 * honest and keeps the console presentable at every phase rather than only at the end.
 */
export type EvidenceKey = 'thermal' | 'rgb' | 'rgbAnnotated' | 'audio' | 'flyover';

// `as unknown as`, like every other import above and for the same reason: the JSON
// widens `bbox` to number[] where the schema wants a 4-tuple, and validate:data has
// already parsed this exact file against the Zod schema in prebuild. Narrowing it a
// second time here would re-prove what the gate refuses to ship without.
const artefacts = artefactsJson as unknown as {
  files: Record<EvidenceKey, string | null>;
  detection: Detection | null;
  agent: AgentCache | null;
};

export const evidenceUrl = (key: EvidenceKey): string | null => artefacts.files[key];
export const hasEvidence = (key: EvidenceKey): boolean => artefacts.files[key] !== null;

/**
 * The real model output, or null until Colab lands (Phase 3). Never stub this: the
 * entire point of the reticle is that its confidence is a measurement, and
 * invariant I11 rejects the spec's placeholder 0.84 by name.
 */
export const detection: Detection | null = artefacts.detection;

/**
 * The arrays we hold real captured imagery for.
 *
 * Exactly one. `b17_cellgrid.json` is a measurement from a specific Raptor Maps
 * thermal frame and `b17_detection.json` is a specific model output on a specific
 * held-out image — neither describes array A-03, and rendering them under A-03's
 * name would be presenting one array's evidence as another's. That is the same
 * failure as quoting B-17's agent prose for every array, and it gets the same
 * answer: say there is no capture on file.
 *
 * A second entry only ever appears here alongside a second real capture.
 */
export const ARRAYS_WITH_CAPTURED_EVIDENCE = new Set(['B-17']);

export const hasCapturedEvidence = (panelId: string): boolean =>
  ARRAYS_WITH_CAPTURED_EVIDENCE.has(panelId);

/**
 * Cached agent reasoning, or null until Phase 6. The LLM writes prose ABOUT
 * numbers; `run_agent.py` cross-checks every numeric field against telemetry.json
 * and refuses to write a cache that contradicts the physics.
 */
export const agentCache: AgentCache | null = artefacts.agent;

/**
 * Surface material for the 3D modules, and its provenance.
 *
 * WHAT THIS IS NOT. It is not evidence, and `hasCapturedEvidence` does not move
 * because of it. These are photographs of somebody else's panels from a public
 * dataset, put on the render the way a digital twin is textured from site imagery
 * — geometry from the site plan, surface from photography. Every surface that
 * shows one says so, because a photograph on a 3D module is exactly the kind of
 * thing an audience would otherwise read as a camera frame.
 *
 * WHY IT EXISTS. The detector was trained on ground-level photographs. Given a
 * flat-shaded blue rectangle it returns nothing, correctly. Texturing the module
 * is what gives a live run over the render a fair chance of firing at all.
 *
 * `detectorOnTexture` is our own weights' verdict on the written file, measured by
 * `scripts/make_panel_textures.mts`, which refuses to write an intact texture the
 * model calls cracked.
 */
export interface PanelTexture {
  role: 'cracked' | 'intact';
  url: string;
  sourceImage: string;
  split: string;
  datasetLabel: string;
  rotatedDeg: number;
  widthPx: number;
  heightPx: number;
  detectorOnTexture: { label: string; confidence: number } | null;
}

const panelTextureFile = panelTexturesJson as unknown as {
  dataset: { name: string; source: string; licence: string };
  textures: PanelTexture[];
};

export const panelTextureDataset = panelTextureFile.dataset;

export const panelTexture = (role: PanelTexture['role']): PanelTexture | undefined =>
  panelTextureFile.textures.find((t) => t.role === role);
