import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

/**
 * The rules below are not style. They are the invariants that protect the demo,
 * and they are the cheapest insurance in the project — see plan/02 §7.
 *
 * ONE CLOCK. `t` in src/store/demoClock.ts is the only source of time, advanced by
 * the single rAF loop in src/hooks/useDemoClock.ts. A second timer anywhere is what
 * desyncs the console from the cinematic, and CLAUDE.md §17 ranks it the most likely
 * failure in the whole build. Presentational CSS animation is fine — anything a
 * selector READS must come from `t`.
 */
const ONE_CLOCK_GLOBALS = [
  { name: "setInterval", message: "One clock only. Derive from t — see src/store/demoClock.ts." },
  { name: "setTimeout", message: "One clock only. Derive from t — see src/store/demoClock.ts." },
  { name: "requestAnimationFrame", message: "The only rAF loop lives in src/hooks/useDemoClock.ts." },
];

const NO_SECOND_TIMER = {
  selector:
    "CallExpression[callee.name=/^(setInterval|setTimeout|requestAnimationFrame)$/]",
  message:
    "One clock only. The single rAF loop is in src/hooks/useDemoClock.ts; everything visible is a pure function of t.",
};

const NO_RANDOM = {
  selector: "MemberExpression[object.name='Math'][property.name='random']",
  message:
    "No Math.random() in src/. Telemetry is pre-generated by scripts/generate_telemetry.py and committed.",
};

const NO_STORAGE = {
  selector: "MemberExpression[object.name=/^(localStorage|sessionStorage)$/]",
  message:
    "No browser storage. The only persisted state is the committed JSON in /data.",
};

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  {
    // Everything under src/ — no randomness, no storage.
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": ["error", NO_RANDOM, NO_STORAGE],
    },
  },

  {
    // Components may not own time. useFrame is allowed only in scene/, and only to
    // READ useDemoClock.getState().t — never to accumulate.
    files: ["src/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-globals": ["error", ...ONE_CLOCK_GLOBALS],
      "no-restricted-syntax": ["error", NO_SECOND_TIMER, NO_RANDOM, NO_STORAGE],
    },
  },

  {
    // The one legal exception, written as an exception so it stays visible.
    files: ["src/hooks/useDemoClock.ts"],
    rules: {
      "no-restricted-globals": "off",
      "no-restricted-syntax": ["error", NO_RANDOM, NO_STORAGE],
    },
  },

  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "plan/schemas.ts",   // historical; src/lib/types.ts is the live schema owner
    ],
  },
];

export default eslintConfig;
